import type { Request, Profile } from '@/types/database.types';

export const MOCK_VOLUNTEER: Profile = {
  id: 'vol-123',
  role: 'volunteer',
  full_name: 'Alex Johnson',
  email: 'alex@example.com',
  phone: '555-0199',
  avatar_url: 'https://i.pravatar.cc/150?u=vol-123',
  verified: true,
  rating: 4.9,
  completed_tasks: 42,
  emergency_contact: null,
  bio: 'College student happy to help out around the neighborhood!',
  address: 'Downtown',
  latitude: null,
  longitude: null,
  availability_status: 'available',
  impact_score: 1250,
  created_at: new Date().toISOString(),
  updated_at: new Date().toISOString(),
};

export const MOCK_REQUESTS: Request[] = [
  {
    id: 'req-1',
    requester_id: 'me',
    volunteer_id: 'vol-123',
    category: 'grocery',
    title: 'Need a few items from local bakery',
    description: 'Just need milk, bread, and some fresh fruit. Thank you!',
    priority: 'normal',
    status: 'assigned',
    preferred_time: new Date(Date.now() + 86400000).toISOString(), // tomorrow
    address: 'Petta Junction, Kanjirappally',
    latitude: 9.5540,
    longitude: 76.7875,
    special_instructions: 'Please ring the doorbell twice.',
    created_at: new Date(Date.now() - 3600000).toISOString(),
    updated_at: new Date(Date.now() - 3600000).toISOString(),
  },
  {
    id: 'req-2',
    requester_id: 'me',
    volunteer_id: null,
    category: 'medication',
    title: 'Pharmacy pick up at Medical Trust',
    description: 'My prescription is ready at the pharmacy near Medical Trust Hospital.',
    priority: 'high',
    status: 'submitted',
    preferred_time: null,
    address: 'Hospital Road, Kanjirappally',
    latitude: 9.5562,
    longitude: 76.7891,
    special_instructions: null,
    created_at: new Date(Date.now() - 86400000).toISOString(),
    updated_at: new Date(Date.now() - 86400000).toISOString(),
  },
  {
    id: 'req-3',
    requester_id: 'user-789',
    volunteer_id: null,
    category: 'companionship',
    title: 'Looking for a quick chat and tea',
    description: 'I would love some company this afternoon if anyone is free to drop by for a cup of tea.',
    priority: 'low',
    status: 'submitted',
    preferred_time: new Date(Date.now() + 7200000).toISOString(), // 2 hours from now
    address: 'AKJM Public School Road, Kanjirappally',
    latitude: 9.5535,
    longitude: 76.7850,
    special_instructions: 'Please check in at the front desk.',
    created_at: new Date(Date.now() - 3600000).toISOString(),
    updated_at: new Date(Date.now() - 3600000).toISOString(),
  }
];
